name: Build docker

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build-wasm:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          install_args: "node@latest pnpm@latest"
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build wasm
        run: |
          cd ./wasm
          wasm-pack build --release --target web
          cd ./js
          pnpm i
          pnpm run build
      - name: Rename artifact
        run: |
          mkdir out
          mv wasm/pkg/index.html out
          mv wasm/pkg/client.js out
      - name: Upload artifact(html)
        uses: actions/upload-artifact@v7
        with:
          name: html
          path: out/index.html
      - name: Upload artifact(js)
        uses: actions/upload-artifact@v7
        with:
          name: js
          path: out/client.js
  build:
    name: Build docker
    needs: [ build-wasm ]
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        include:
          - rusttarget: aarch64-unknown-linux-gnu
            platform: arm64
          - rusttarget: x86_64-unknown-linux-gnu
            platform: amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Downlaod artifact(html)
        run: gh run download ${{ github.run_id }} -p html
      - name: Downlaod artifact(js)
        run: gh run download ${{ github.run_id }} -p js
      - name: Rename paths
        run: |
          mkdir wasm/pkg
          mv html/index.html wasm/pkg
          mv js/client.js wasm/pkg
      - name: Build cross platform rust binary
        uses: neodyland/cross-rust-action@v0.1.16
        with:
          target: ${{ matrix.rusttarget }}
          cargo-build-args: --release

      - name: Rename artifact
        run: |
          mkdir out
          mkdir out/ii-diff
          mv target/${{ matrix.rusttarget }}/release/iidiff-server out/ii-diff/binary-${{ matrix.platform }}

      - name: Upload ii-diff
        uses: actions/upload-artifact@v7
        with:
          name: ii-diff-${{ matrix.platform }}
          path: out/ii-diff/binary-${{ matrix.platform }}

  release:
    name: Release docker image
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GH_TOKEN: ${{ github.token }}
      IMAGE_NAME_PREFIX: 11diff
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Downlaod ii-diff
        run: gh run download ${{ github.run_id }} -p ii-diff-*

      - name: Rename paths
        run: |
          mkdir .out
          mv ii-diff-*/binary-* .out/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          file: ./.github/workflows/build.Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME_PREFIX }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME_PREFIX }}:${{ github.sha }}